// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZs2McpwT4ctVY9p1-ogqqoYI2jBgxAe0',
    appId: '1:449550678117:web:20958f66867601354d6e8c',
    messagingSenderId: '449550678117',
    projectId: 'libralink-7c0e5',
    authDomain: 'libralink-7c0e5.firebaseapp.com',
    storageBucket: 'libralink-7c0e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wQigwfiSYfEpC6RMdQLAAldBdYTqqbE',
    appId: '1:449550678117:android:bc0ca3ee3c924a204d6e8c',
    messagingSenderId: '449550678117',
    projectId: 'libralink-7c0e5',
    storageBucket: 'libralink-7c0e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcGWnVTxISJe6N4QgtCCUqzoImm0vpdKA',
    appId: '1:449550678117:ios:3c3b04f8336596a64d6e8c',
    messagingSenderId: '449550678117',
    projectId: 'libralink-7c0e5',
    storageBucket: 'libralink-7c0e5.appspot.com',
    iosBundleId: 'com.example.libralink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcGWnVTxISJe6N4QgtCCUqzoImm0vpdKA',
    appId: '1:449550678117:ios:3c3b04f8336596a64d6e8c',
    messagingSenderId: '449550678117',
    projectId: 'libralink-7c0e5',
    storageBucket: 'libralink-7c0e5.appspot.com',
    iosBundleId: 'com.example.libralink',
  );
}
